# STAT 440 Statistical Data Management - Fall 2021
## Week 07 Notes
### Created by Christopher Kinson


***

### Table of Contents

- [Regular Expressions and String Manipulation](#regex)  
  - [Examples with City of Urbana's Rental Inspection Grades Listing Data](#examples)


***


## <a name="regex"></a>Regular Expressions and String Manipulation

In this section, we discuss typical operations for string manipulation and subsetting based on characters. Character strings can be quite difficult to wrangle. This difficulty may be due to character encoding and differences in how computers interpret strings. One alleviation of this difficulty was conceptualized in the 1950s by Stephen Kleene called regular expressions (or regex for short). A regular expression is a standardized pattern for finding strings and characters. Regex exists separate from programming languages (much like SQL) and is usually incorporated via a library or module. 

Regex can be used to pick out or match certain characters in a character vector, and this is helpful for subsetting strings. Regex can be used in Python within the `pandas` and `re` packages. Read more here [Regular expressions documentation](https://docs.python.org/3/library/re.html). The table's example is the following sentence: 

    "Friends of the Geese are hosting a memorial service Saturday for the 175 geese killed this week by the Urbana Park District in its 'charity harvest.'"

Regex Syntax | Explanation | Matching String Found
---|---|---|
\\w |any letter or digit | "FriendsoftheGeesearehostingamemorialserviceSaturdayforthe175geesekilledthisweekbytheUrbanaParkDistrictinitscharityharvest"
\\d | any digit | "175"
[\\.\\'] | only the period and apostrophe | "'.'"
[^\\.] | anything but not the period | "Friends of the Geese are hosting a memorial service Saturday for the 175 geese killed this week by the Urbana Park District in its 'charity harvest'"
[A-M] | anything with capital letters A-M| "FriendsGeeseDistrict"
s+ | any words or characters with the letter s and anything after the s| "FriendsGeesehostingservicegeesethisDistrictitsharvest"
s+\|S+ | any words or characters with the letter s or capital S and anything after the s or capital S | "FriendsGeesehostingserviceSaturdaygeesethisDistrictitsharvest"
e{2} | any word with exactly two consecutive letter e| "Geesegeeseweek"

See https://kanoki.org/2019/11/12/how-to-use-regex-in-pandas/ for more regex syntax and opportunities to test out regular expressions.

Below is an Python code chunk as evidence of the regex usage along with some **re** package functions. These **re** functions are vectorized and return a value for each element in the input vector:

- `findall`: find all matched pattern

- `replace`: replaces the matched pattern with another string

- `count`: counts the number of times the pattern is matched

In [1]:
import pandas as pd
import numpy as np
ss = pd.Series(["Friends of the Geese are hosting a memorial service Saturday for the 175 geese killed this week by the Urbana Park District in its 'charity harvest.'"])

In [2]:
ss.str.findall('\w')[0] #str_extract(ss, "\\w")

['F',
 'r',
 'i',
 'e',
 'n',
 'd',
 's',
 'o',
 'f',
 't',
 'h',
 'e',
 'G',
 'e',
 'e',
 's',
 'e',
 'a',
 'r',
 'e',
 'h',
 'o',
 's',
 't',
 'i',
 'n',
 'g',
 'a',
 'm',
 'e',
 'm',
 'o',
 'r',
 'i',
 'a',
 'l',
 's',
 'e',
 'r',
 'v',
 'i',
 'c',
 'e',
 'S',
 'a',
 't',
 'u',
 'r',
 'd',
 'a',
 'y',
 'f',
 'o',
 'r',
 't',
 'h',
 'e',
 '1',
 '7',
 '5',
 'g',
 'e',
 'e',
 's',
 'e',
 'k',
 'i',
 'l',
 'l',
 'e',
 'd',
 't',
 'h',
 'i',
 's',
 'w',
 'e',
 'e',
 'k',
 'b',
 'y',
 't',
 'h',
 'e',
 'U',
 'r',
 'b',
 'a',
 'n',
 'a',
 'P',
 'a',
 'r',
 'k',
 'D',
 'i',
 's',
 't',
 'r',
 'i',
 'c',
 't',
 'i',
 'n',
 'i',
 't',
 's',
 'c',
 'h',
 'a',
 'r',
 'i',
 't',
 'y',
 'h',
 'a',
 'r',
 'v',
 'e',
 's',
 't']

In [3]:
ss.str.findall('[^\.]')[0] #str_extract_all(ss, "[^\\.]")

['F',
 'r',
 'i',
 'e',
 'n',
 'd',
 's',
 ' ',
 'o',
 'f',
 ' ',
 't',
 'h',
 'e',
 ' ',
 'G',
 'e',
 'e',
 's',
 'e',
 ' ',
 'a',
 'r',
 'e',
 ' ',
 'h',
 'o',
 's',
 't',
 'i',
 'n',
 'g',
 ' ',
 'a',
 ' ',
 'm',
 'e',
 'm',
 'o',
 'r',
 'i',
 'a',
 'l',
 ' ',
 's',
 'e',
 'r',
 'v',
 'i',
 'c',
 'e',
 ' ',
 'S',
 'a',
 't',
 'u',
 'r',
 'd',
 'a',
 'y',
 ' ',
 'f',
 'o',
 'r',
 ' ',
 't',
 'h',
 'e',
 ' ',
 '1',
 '7',
 '5',
 ' ',
 'g',
 'e',
 'e',
 's',
 'e',
 ' ',
 'k',
 'i',
 'l',
 'l',
 'e',
 'd',
 ' ',
 't',
 'h',
 'i',
 's',
 ' ',
 'w',
 'e',
 'e',
 'k',
 ' ',
 'b',
 'y',
 ' ',
 't',
 'h',
 'e',
 ' ',
 'U',
 'r',
 'b',
 'a',
 'n',
 'a',
 ' ',
 'P',
 'a',
 'r',
 'k',
 ' ',
 'D',
 'i',
 's',
 't',
 'r',
 'i',
 'c',
 't',
 ' ',
 'i',
 'n',
 ' ',
 'i',
 't',
 's',
 ' ',
 "'",
 'c',
 'h',
 'a',
 'r',
 'i',
 't',
 'y',
 ' ',
 'h',
 'a',
 'r',
 'v',
 'e',
 's',
 't',
 "'"]

In [4]:
ss.str.replace("\.\'","",n=1)[0] #str_remove(ss, "\\.\\'")

"Friends of the Geese are hosting a memorial service Saturday for the 175 geese killed this week by the Urbana Park District in its 'charity harvest"

In [5]:
ss.str.replace("\d","", n=1)[0] #str_remove(ss, "\\d")

"Friends of the Geese are hosting a memorial service Saturday for the 75 geese killed this week by the Urbana Park District in its 'charity harvest.'"

In [6]:
ss.str.replace("\d","")[0] #str_remove_all(ss, "\\d")

"Friends of the Geese are hosting a memorial service Saturday for the  geese killed this week by the Urbana Park District in its 'charity harvest.'"

In [7]:
ss.str.replace("[A-M]","", n=1)[0] #str_remove(ss, "[A-M]")

"riends of the Geese are hosting a memorial service Saturday for the 175 geese killed this week by the Urbana Park District in its 'charity harvest.'"

In [8]:
ss.str.replace("[A-M]","")[0] #str_remove_all(ss, "[A-M]")

"riends of the eese are hosting a memorial service Saturday for the 175 geese killed this week by the Urbana Park istrict in its 'charity harvest.'"

In [9]:
ss.str.replace("s+|S+", "Que", n=1)[0] #str_replace(ss, "s+|S+", "Que")

"FriendQue of the Geese are hosting a memorial service Saturday for the 175 geese killed this week by the Urbana Park District in its 'charity harvest.'"

In [10]:
ss.str.replace("s+|S+", "Que")[0] #str_replace_all(ss, "s+|S+", "Que")

"FriendQue of the GeeQuee are hoQueting a memorial Queervice Queaturday for the 175 geeQuee killed thiQue week by the Urbana Park DiQuetrict in itQue 'charity harveQuet.'"

In [11]:
ss.str.count("e{2}")[0] #str_count(ss, "e{2}")

3


### <a name="examples"></a>Examples with City of Urbana's Rental Inspection Grades Listing Data

Working with the City of Urbana's [Rental Inspection Grades Listing Data as tab-separated .txt](https://github-dev.cs.illinois.edu/stat440-fa21/stat440-fa21-course-content/raw/master/data/rental-inspections-grades-data03.txt), we can finally explain what we did to the "Mappable Address" column in the Week 04 notes.

In [12]:
RentalsData = pd.read_table('https://raw.github-dev.cs.illinois.edu/stat440-fa21/stat440-fa21-course-content/master/data/rental-inspections-grades-data03.txt?token=AAABJG7SICDEHN7MZMWD47DBGPBBM')
RentalsData.head(10)

,Property Address,Parcel Number,Inspection Date,Grade,License Status,Expiration Date,Mappable Address
0,607 1/2 Glover Avenue,9.221162e+11,7/24/2015,Class B,Expired,10/14/2021,"607 1 2 Glover Avenue\nUrbana, IL\n(40.108023,..."
1,1302 1/2 Hill Street,9.121074e+11,8/17/2011,Class B,Issued,10/14/2021,"1302 1 2 Hill Street\nUrbana, IL\n(40.119327, ..."
2,212 1/2 Central Avenue,9.121084e+11,4/26/2010,Class B,Issued,NaN,"212 1 2 Central Avenue\nUrbana, IL"
3,801 1/2 East Harding Drive,9.321212e+11,6/12/2013,Class B,Issued,10/14/2021,"801 1 2 East Harding Drive\nUrbana, IL\n(40.09..."
4,1003 1/2 East Harding Drive,9.321212e+11,7/8/2013,Class B,Issued,10/14/2020,"1003 1 2 East Harding Drive\nUrbana, IL\n(40.0..."
5,1204 1/2 North Goodwin Avenue,9.121073e+11,10/20/2011,Class B,Issued,10/14/2021,"1204 1 2 North Goodwin Avenue\nUrbana, IL\n(40..."
6,910 1/2 North Busey Avenue,9.121082e+11,12/17/2010,Class B,Issued,10/14/2021,"910 1 2 North Busey Avenue\nUrbana, IL\n(40.12..."
7,1109 1/2 East Main Street,9.221161e+11,6/5/2015,Class B,Issued,10/14/2020,"1109 1 2 East Main Street\nUrbana, IL\n(40.112..."
8,1306 1/2 East Mumford Drive,9.321213e+11,7/8/2013,Class B,Issued,10/14/2021,"1306 1 2 East Mumford Drive\nUrbana, IL\n(40.0..."
9,807 1/2 West Main Street,9.121084e+11,5/18/2011,Class A,Issued,10/14/2020,"807 1 2 West Main Street\nUrbana, IL\n(40.1144..."

First, we used **numpy**'s `split()` function to separate the character strings originally found in "Mappable Address" into 3 columns, where `\n` is the separator that determined how to split them up.

In [13]:
import numpy as np
n = len(RentalsData['Mappable Address'][0].split('\n'))
# use condition to justify whether it is nan value
addr = RentalsData['Mappable Address'].apply(lambda x: {i: x.split('\n')[i] 
                                                            if i<len(x.split('\n')) else np.nan for i in range(n) })
Coordinates = pd.DataFrame()
for i in range(n):
    Coordinates[str(i)] = [x[i] for x in addr]
Coordinates.head(10)

                               0           1                        2
0          607 1 2 Glover Avenue  Urbana, IL  (40.108023, -88.193322)
1           1302 1 2 Hill Street  Urbana, IL  (40.119327, -88.226119)
2         212 1 2 Central Avenue  Urbana, IL                      NaN
3     801 1 2 East Harding Drive  Urbana, IL   (40.093806, -88.19767)
4    1003 1 2 East Harding Drive  Urbana, IL  (40.093743, -88.195595)
5  1204 1 2 North Goodwin Avenue  Urbana, IL   (40.123423, -88.22415)
6     910 1 2 North Busey Avenue  Urbana, IL  (40.120904, -88.216957)
7      1109 1 2 East Main Street  Urbana, IL  (40.112983, -88.195041)
8    1306 1 2 East Mumford Drive  Urbana, IL  (40.090691, -88.192163)
9       807 1 2 West Main Street  Urbana, IL  (40.114488, -88.218406)

In [14]:
Coordinates.tail(10)

,0,1,2
1720,401 South Poplar Street,"Urbana, IL","(-88.1949, 40.1099)"
1721,706 South Coler Avenue,"Urbana, IL","(-88.2158, 40.1068)"
1722,401 West Springfield Avenue,"Urbana, IL","(40.112118, -88.211975)"
1723,1301 1 2 Dublin Street,"Urbana, IL","(-88.2258, 40.1212)"
1724,2005 Bruce Drive,"Urbana, IL","(-88.1932, 40.0928)"
1725,3026 East Stillwater Landing,"Urbana, IL","(40.090282, -88.16565)"
1726,1108 South Busey Avenue,"Urbana, IL","(40.1031074524, -88.2173538208)"
1727,806 Harvey Street,"Urbana, IL","(-88.2215, 40.1198)"
1728,1302 East Michigan Avenue,"Urbana, IL","(-88.1929, 40.1017)"
1729,1503 South Cottage Grove Avenue,"Urbana, IL","(-88.1959, 40.0996)"

Notice that several of the first few addresses in `Coordinates` are written with the string "1 2" in the first column. These are addresses which have "1/2" units - a common designation for apartments or very small residences. We can use `str.replace()` to find all "1 2" strings and replace them with `1/2" strings.

In [15]:
Coordinates.iloc[:,0] = Coordinates.iloc[:,0].str.replace('1\s2','1/2')
Coordinates.head(10)

                               0           1                        2
0          607 1/2 Glover Avenue  Urbana, IL  (40.108023, -88.193322)
1           1302 1/2 Hill Street  Urbana, IL  (40.119327, -88.226119)
2         212 1/2 Central Avenue  Urbana, IL                      NaN
3     801 1/2 East Harding Drive  Urbana, IL   (40.093806, -88.19767)
4    1003 1/2 East Harding Drive  Urbana, IL  (40.093743, -88.195595)
5  1204 1/2 North Goodwin Avenue  Urbana, IL   (40.123423, -88.22415)
6     910 1/2 North Busey Avenue  Urbana, IL  (40.120904, -88.216957)
7      1109 1/2 East Main Street  Urbana, IL  (40.112983, -88.195041)
8    1306 1/2 East Mumford Drive  Urbana, IL  (40.090691, -88.192163)
9       807 1/2 West Main Street  Urbana, IL  (40.114488, -88.218406)

In [16]:
Coordinates.tail(10)

,0,1,2
1720,401 South Poplar Street,"Urbana, IL","(-88.1949, 40.1099)"
1721,706 South Coler Avenue,"Urbana, IL","(-88.2158, 40.1068)"
1722,401 West Springfield Avenue,"Urbana, IL","(40.112118, -88.211975)"
1723,1301 1/2 Dublin Street,"Urbana, IL","(-88.2258, 40.1212)"
1724,2005 Bruce Drive,"Urbana, IL","(-88.1932, 40.0928)"
1725,3026 East Stillwater Landing,"Urbana, IL","(40.090282, -88.16565)"
1726,1108 South Busey Avenue,"Urbana, IL","(40.1031074524, -88.2173538208)"
1727,806 Harvey Street,"Urbana, IL","(-88.2215, 40.1198)"
1728,1302 East Michigan Avenue,"Urbana, IL","(-88.1929, 40.1017)"
1729,1503 South Cottage Grove Avenue,"Urbana, IL","(-88.1959, 40.0996)"

We can see some elements of the second column of `Coordinates` are not simply "Urbana, IL", but contain specific apartment numbers or unit numbers.

In [17]:
Coordinates.iloc[:,1].str.findall('^Urbana\,\sIL').apply(lambda x: len(x)<1).sum()

38

Let's mutate with 2 new columns: City which should always be equal to "Urbana" and State which will always equal "IL" and de-select the second column. This means that Coordinates will now have 4 columns total.

In [18]:
Coordinates['City'] = 'Urbana'
Coordinates['State'] = 'IL'
Coordinates = Coordinates.drop(columns=['1'])
Coordinates.head(10)

                               0                        2    City State
0          607 1/2 Glover Avenue  (40.108023, -88.193322)  Urbana    IL
1           1302 1/2 Hill Street  (40.119327, -88.226119)  Urbana    IL
2         212 1/2 Central Avenue                      NaN  Urbana    IL
3     801 1/2 East Harding Drive   (40.093806, -88.19767)  Urbana    IL
4    1003 1/2 East Harding Drive  (40.093743, -88.195595)  Urbana    IL
5  1204 1/2 North Goodwin Avenue   (40.123423, -88.22415)  Urbana    IL
6     910 1/2 North Busey Avenue  (40.120904, -88.216957)  Urbana    IL
7      1109 1/2 East Main Street  (40.112983, -88.195041)  Urbana    IL
8    1306 1/2 East Mumford Drive  (40.090691, -88.192163)  Urbana    IL
9       807 1/2 West Main Street  (40.114488, -88.218406)  Urbana    IL

In [19]:
Coordinates.tail(10)

,0,2,City,State
1720,401 South Poplar Street,"(-88.1949, 40.1099)",Urbana,IL
1721,706 South Coler Avenue,"(-88.2158, 40.1068)",Urbana,IL
1722,401 West Springfield Avenue,"(40.112118, -88.211975)",Urbana,IL
1723,1301 1/2 Dublin Street,"(-88.2258, 40.1212)",Urbana,IL
1724,2005 Bruce Drive,"(-88.1932, 40.0928)",Urbana,IL
1725,3026 East Stillwater Landing,"(40.090282, -88.16565)",Urbana,IL
1726,1108 South Busey Avenue,"(40.1031074524, -88.2173538208)",Urbana,IL
1727,806 Harvey Street,"(-88.2215, 40.1198)",Urbana,IL
1728,1302 East Michigan Avenue,"(-88.1929, 40.1017)",Urbana,IL
1729,1503 South Cottage Grove Avenue,"(-88.1959, 40.0996)",Urbana,IL

Now, there is trouble with the now second column of `Coordinates` (which is now a **DataFrame**). 

Do you see trouble? 

You probably do not recognize the issue, but some elements of the second column have the GPS cordinates - representing latitude and longitude - in the incorrect position. Urbana's centralized coordinates are 40.10972, -88.204167 (i.e. lat,lon).

In [20]:
Coordinates.head(30)

                                 0                        2    City State
0            607 1/2 Glover Avenue  (40.108023, -88.193322)  Urbana    IL
1             1302 1/2 Hill Street  (40.119327, -88.226119)  Urbana    IL
2           212 1/2 Central Avenue                      NaN  Urbana    IL
3       801 1/2 East Harding Drive   (40.093806, -88.19767)  Urbana    IL
4      1003 1/2 East Harding Drive  (40.093743, -88.195595)  Urbana    IL
5    1204 1/2 North Goodwin Avenue   (40.123423, -88.22415)  Urbana    IL
6       910 1/2 North Busey Avenue  (40.120904, -88.216957)  Urbana    IL
7        1109 1/2 East Main Street  (40.112983, -88.195041)  Urbana    IL
8      1306 1/2 East Mumford Drive  (40.090691, -88.192163)  Urbana    IL
9         807 1/2 West Main Street  (40.114488, -88.218406)  Urbana    IL
10       709 1/2 South Vine Street  (40.106827, -88.204932)  Urbana    IL
11       906 1/2 South Vine Street  (40.105011, -88.204986)  Urbana    IL
12   1204 1/2 East Michigan Avenue  (40.101585, -88.193961)  Urbana    IL
13           712 1/2 Wabash Avenue  (40.106706, -88.196627)  Urbana    IL
14      2001 1/2 East Rainbow View  (40.103169, -88.183587)  Urbana    IL
15             601 A Glover Avenue  (40.108517, -88.193331)  Urbana    IL
16      601 1/2 East Mumford Drive  (40.090671, -88.200314)  Urbana    IL
17  601 1/2 West California Avenue  (40.108318, -88.214591)  Urbana    IL
18        108 L North Busey Avenue  (40.113198, -88.217734)  Urbana    IL
19         604 1/2 West Elm Street  (40.111501, -88.215083)  Urbana    IL
20     2203 1/2 Lantern Hill Drive  (40.104243, -88.179517)  Urbana    IL
21         606 1/2 West Elm Street  (40.111499, -88.215277)  Urbana    IL
22   1202 1/2 East Michigan Avenue  (40.101602, -88.194214)  Urbana    IL
23            1210 1/2 Hill Street  (40.119329, -88.225289)  Urbana    IL
24      1408 1/2 South Vine Street   (40.09987, -88.204907)  Urbana    IL
25         707 1/2 Anderson Street   (40.10711, -88.200223)  Urbana    IL
26   1206 1/2 East Michigan Avenue  (40.101555, -88.193696)  Urbana    IL
27      702 1/2 West Nevada Street  (40.106511, -88.216193)  Urbana    IL
28        804 1/2 East Main Street  (40.112998, -88.198791)  Urbana    IL
29          511 West Oregon Street      (-88.2143, 40.1073)  Urbana    IL

In [21]:
Coordinates.tail(30)

,0,2,City,State
1700,1208 Eastern Drive,"(-88.1932, 40.1039)",Urbana,IL
1701,904 North Broadway Avenue,"(-88.2076, 40.1206)",Urbana,IL
1702,3 Rainbow Court,"(-88.1838, 40.1038)",Urbana,IL
1703,709 Western Avenue,"(-88.2171, 40.112)",Urbana,IL
1704,706 Anderson Street,"(-88.2, 40.1071)",Urbana,IL
1705,1203 East Willard Street,"(40.084072, -88.193)",Urbana,IL
1706,1511 Lincolnwood Drive,"(-88.1856, 40.0997)",Urbana,IL
1707,2211 South Philo Road,"(40.08879, -88.190956)",Urbana,IL
1708,113 Franklin Street,"(-88.2091, 40.1206)",Urbana,IL
1709,805 North Coler Avenue,"(-88.2161, 40.1196)",Urbana,IL
1710,705 West Oregon Street,"(-88.2166, 40.1072)",Urbana,IL
1711,1406 Eastern Drive,"(-88.1918, 40.1029)",Urbana,IL
1712,814 West Main Street,"(-88.2189, 40.1148)",Urbana,IL
1713,904 North Broadway Avenue,"(-88.2076, 40.1206)",Urbana,IL
1714,106 Glover Avenue,"(-88.1931, 40.1124)",Urbana,IL
1715,1726 East Florida Avenue,"(-88.1859, 40.0985)",Urbana,IL
1716,501 Sunny Lane,"(-88.1729, 40.1083)",Urbana,IL
1717,1004 Garfield Avenue,"(-88.2109, 40.1044)",Urbana,IL
1718,1205 East Harding Drive,"(-88.1932, 40.0936)",Urbana,IL
1719,1005 East Washington Street,"(-88.1961, 40.1054)",Urbana,IL
1720,401 South Poplar Street,"(-88.1949, 40.1099)",Urbana,IL
1721,706 South Coler Avenue,"(-88.2158, 40.1068)",Urbana,IL
1722,401 West Springfield Avenue,"(40.112118, -88.211975)",Urbana,IL
1723,1301 1/2 Dublin Street,"(-88.2258, 40.1212)",Urbana,IL
1724,2005 Bruce Drive,"(-88.1932, 40.0928)",Urbana,IL
1725,3026 East Stillwater Landing,"(40.090282, -88.16565)",Urbana,IL
1726,1108 South Busey Avenue,"(40.1031074524, -88.2173538208)",Urbana,IL
1727,806 Harvey Street,"(-88.2215, 40.1198)",Urbana,IL
1728,1302 East Michigan Avenue,"(-88.1929, 40.1017)",Urbana,IL
1729,1503 South Cottage Grove Avenue,"(-88.1959, 40.0996)",Urbana,IL

This means that it's best to place the numbers beginning with "40" in the first position before the comma, then the number beginning with "-88" in the second position.

In [22]:
Coordinates00 = Coordinates['2'].str.replace('\)|\,|\(','')
Coordinates000 = Coordinates00.str.split(" ")
RentalsData['Coordinates01'] = [float(x[0]) if x==x else np.nan for x in Coordinates000]
RentalsData['Coordinates02'] = [float(x[1]) if x==x else np.nan for x in Coordinates000]
RentalsData.tail(10)

,Property Address,Parcel Number,Inspection Date,Grade,License Status,Expiration Date,Mappable Address,Coordinates01,Coordinates02
1720,401 South Poplar Street,9.221161e+11,6/29/2012,Class B,Issued,NaN,"401 South Poplar Street\nUrbana, IL\n(-88.1949...",-88.194900,40.109900
1721,706 South Coler Avenue,9.221172e+11,3/31/2008,Class B,Issued,NaN,"706 South Coler Avenue\nUrbana, IL\n(-88.2158,...",-88.215800,40.106800
1722,401 West Springfield Avenue,9.221171e+11,3/4/2019,Class B,Issued,10/14/2021,"401 West Springfield Avenue\nUrbana, IL\n(40.1...",40.112118,-88.211975
1723,1301 1/2 Dublin Street,9.121073e+11,6/29/2011,Class B,Expired,NaN,"1301 1 2 Dublin Street\nUrbana, IL\n(-88.2258,...",-88.225800,40.121200
1724,2005 Bruce Drive,9.321212e+11,6/4/2013,Class A,Issued,10/14/2021,"2005 Bruce Drive\nUrbana, IL\n(-88.1932, 40.0928)",-88.193200,40.092800
1725,3026 East Stillwater Landing Unit 101,9.321224e+11,12/18/2017,Class B,Issued,10/14/2021,"3026 East Stillwater Landing\nUrbana, IL\n(40....",40.090282,-88.165650
1726,1108 South Busey Avenue,9.321173e+11,12/16/2019,Class B,Issued,10/14/2021,"1108 South Busey Avenue\nUrbana, IL\n(40.10310...",40.103107,-88.217354
1727,806 Harvey Street,9.121074e+11,11/4/2011,Class B,Issued,10/14/2021,"806 Harvey Street\nUrbana, IL\n(-88.2215, 40.1...",-88.221500,40.119800
1728,1302 East Michigan Avenue,9.221164e+11,4/18/2016,Class B,Issued,NaN,"1302 East Michigan Avenue\nUrbana, IL\n(-88.19...",-88.192900,40.101700
1729,1503 South Cottage Grove Avenue,9.221164e+11,5/18/2016,Class B,Expired,NaN,"1503 South Cottage Grove Avenue\nUrbana, IL\n(...",-88.195900,40.099600

We just split the coordinates as they originally appeared, but we still have not corrected the coordinates. To do this, we can use the conditional execution.

In [23]:
c01 = [float(x[1]) if ((x==x) and (float(x[0])<0)) else x[0] if x==x else np.nan for x in Coordinates000]
c02 = [float(x[0]) if ((x==x) and (float(x[1])>0)) else x[1] if x==x else np.nan for x in Coordinates000]
RentalsData2 = RentalsData
RentalsData2['Latitude'] = c01
RentalsData2['Longitude'] = c02
RentalsData2['City'] = Coordinates['City']
RentalsData2['State'] = Coordinates['State']
RentalsData2 = RentalsData2.drop(columns=['Mappable Address','Coordinates01','Coordinates02'])
RentalsData2.tail(10)

,Property Address,Parcel Number,Inspection Date,Grade,License Status,Expiration Date,Latitude,Longitude,City,State
1720,401 South Poplar Street,9.221161e+11,6/29/2012,Class B,Issued,NaN,40.1099,-88.1949,Urbana,IL
1721,706 South Coler Avenue,9.221172e+11,3/31/2008,Class B,Issued,NaN,40.1068,-88.2158,Urbana,IL
1722,401 West Springfield Avenue,9.221171e+11,3/4/2019,Class B,Issued,10/14/2021,40.112118,-88.211975,Urbana,IL
1723,1301 1/2 Dublin Street,9.121073e+11,6/29/2011,Class B,Expired,NaN,40.1212,-88.2258,Urbana,IL
1724,2005 Bruce Drive,9.321212e+11,6/4/2013,Class A,Issued,10/14/2021,40.0928,-88.1932,Urbana,IL
1725,3026 East Stillwater Landing Unit 101,9.321224e+11,12/18/2017,Class B,Issued,10/14/2021,40.090282,-88.16565,Urbana,IL
1726,1108 South Busey Avenue,9.321173e+11,12/16/2019,Class B,Issued,10/14/2021,40.1031074524,-88.2173538208,Urbana,IL
1727,806 Harvey Street,9.121074e+11,11/4/2011,Class B,Issued,10/14/2021,40.1198,-88.2215,Urbana,IL
1728,1302 East Michigan Avenue,9.221164e+11,4/18/2016,Class B,Issued,NaN,40.1017,-88.1929,Urbana,IL
1729,1503 South Cottage Grove Avenue,9.221164e+11,5/18/2016,Class B,Expired,NaN,40.0996,-88.1959,Urbana,IL

Trouble is no more!

#### END OF NOTES